### ISSUE TITLE
rebuild_index problem (optparse?)

### ISSUE THREAD

**Issue by dekoza** [toastdriven/django-haystack#1140]
When I try to run rebuild_index, I get this error:
``` tracebak
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/minder/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/minder/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/minder/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/base.py", line 284, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/home/minder/.virtualenvs/project/lib/python2.7/site-packages/django/core/management/base.py", line 265, in create_parser
    option_list=self.option_list)
  File "/usr/lib64/python2.7/optparse.py", line 1220, in __init__
    add_help=add_help_option)
  File "/usr/lib64/python2.7/optparse.py", line 1262, in _populate_option_list
    self.add_options(option_list)
  File "/usr/lib64/python2.7/optparse.py", line 1040, in add_options
    self.add_option(option)
  File "/usr/lib64/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/lib64/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option --nocommit: conflicting option string(s): --nocommit
```

**Comment by acdha** [comment]
Indeed – that was caused by an oversight in #1090 which lacked a test of the actual optparse code (using `call_command()` worked as expected). I'm waiting for the tests to finish before merging https://github.com/acdha/django-haystack/commit/2a958b92c7cf2db90e983687146c233108e8479b
